#!/bin/bash

# create image with name docker-opencv from Dockerfile in ./docker-opencv
# if the image is already built, then it is just tagged with docker-opencv
docker build --no-cache -t babazaroni/docker-opencv .

#run the image with the bash command.
# readlink -f shared  returns the full path of the directory shared in the current directory
  
#docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --runtime=nvidia --name CCTagHost -v $(readlink -f shared):/shared -i -t babazaroni/docker-opencv  /bin/bash


#CTRL pq  will deatach from the running container


#https://stackoverflow.com/questions/35860527/warning-error-disabling-address-space-randomization-operation-not-permitted
#docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined

